### ISSUE TITLE
Complete Missing Methods

### ISSUE THREAD

**Issue by SafaElmali** [SafaElmali/browser-analytics#1]
This package gets some browser metrics and sends it to the Backend server. Help me to complete the incompleted methods 🙋‍♂️

**Comment by maruthimohan** [comment]
Hey @SafaElmali , can I work on this?

**Comment by SafaElmali** [comment]
> Hey @SafaElmali , can I work on this?

Sure. Go ahead :)

**Comment by sambhavjain9138** [comment]
Hello @SafaElmali @maruthimohan . Incase no one is working on the issue, can I work on it?

**Comment by SafaElmali** [comment]
> Hello @SafaElmali @maruthimohan . Incase no one is working on the issue, can I work on it?

Yeah sure!

**Comment by sambhavjain9138** [comment]
Heyy @SafaElmali 
I implemented the 3 missing functions but i am unsure of how to test my code. can you please guide me on the same?

Regards,
Sambhav

**Comment by SafaElmali** [comment]
> Heyy @SafaElmali
> I implemented the 3 missing functions but i am unsure of how to test my code. can you please guide me on the same?
> 
> Regards,
> Sambhav

Hey Sambhav,

I am really new about creating npm packages and this is my first package so there can be problems :) 

First of all, I need to say that the API Endpoint must be your server-side endpoint.

Here is how I use this package: 
- I created a client app such as a React project and I created a serve-side project with express and implemented a post   endpoint to it. 
In my React project, I call the package like this:

```js
useEffect(() => {
 const metric = new BrowserAnalytics({ apiEndpoint: "http://localhost:3001/metrics" })
 const pendingRes = metric.sendMetrics();
  pendingRes.then(result => result.json()).then(formattedRes=>console.log(formattedRes));
})
```

If you are not familiar with React this can confuse you :) 

My Express POST endpoint is like this:

```js
metricsRouter.post('/', function (req, res) {
    const metrics = req.body;
  
         // do some stuff
            ...
            res.send(metrics);
        }
    });
})
```

**Comment by SafaElmali** [comment]
@sambhavjain9138 You can open a merge request and we can review it together if you want
